name: lint-and-test

on:
  push:
    branches:
      - "*-dev"
  pull_request:
    types:
      - closed

jobs:
  lint-and-test:
    # we don't wanna run on the release-please branch or when the release-please branch has been merged
    if: {%raw%}${{ !(startsWith(github.ref_name, 'release-please') || startsWith(github.head_ref, 'release-please'))}}{%endraw%}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python {%raw%}${{ matrix.python-version }}{%endraw%}
      uses: actions/setup-python@v2
      with:
        python-version: {%raw%}${{ matrix.python-version }}{%endraw%}

    - name: Install dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Prepare poetry
      run: |
        poetry config virtualenvs.in-project true
        poetry install

    - name: Run ruff
      run: poetry run nox -s ruff

    - name: Run mypy
      run: poetry run nox -s mypy

    - name: Run tests with nox
      run: poetry run nox -s pytest
