name: pytest

on:
  push:
    branches:
      - "*-dev"
  pull_request:
    types:
      - closed

jobs:
  setup-poetry:
    if: {%raw%}${{ !contains(github.head_ref, 'release-please') }}{%endraw%}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python {%raw%}${{ matrix.python-version }}{%endraw%}
      uses: actions/setup-python@v2
      with:
        python-version: {%raw%}${{ matrix.python-version }}{%endraw%}

    - name: Install dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Prepare poetry
      run: |
        poetry config virtualenvs.in-project true
        poetry install

    - name: Run ruff
      run: poetry run ruff {{ cookiecutter.project_slug }}

    - name: Run mypy
      run: poetry run mypy {{ cookiecutter.project_slug }}

    - name: Run tests with nox
      run: poetry run nox
