name: release please stage 1
on:
  workflow_run:
    workflows: ["lint and test"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    # this job only runs when the original feature PR has been merged and tested
    # it creates the Release-PR
    if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.ref, 'refs/heads/main') && !contains(github.head_ref, 'release-please') }}
    runs-on: ubuntu-latest
    steps:
    - uses: google-github-actions/release-please-action@v3
      with:
        release-type: python
        package-name: citemplate
        token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

