name: release please
on:
  push:
    branches:
    - main
    - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    # this job only runs when a push to main/master happens
    # -> it then creates a release PR and labels it
    # upon merge of the release PR it runs again
    # -> and creates the release
    runs-on: ubuntu-latest
    steps:
    - uses: google-github-actions/release-please-action@v3
      with:
        release-type: python
        package-name: citemplate
        token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

