name: release please stage 2
on:
  push:
    branches:
    - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    # this job only runs to create the final release
    if: ${{ startsWith(github.ref, 'refs/heads/main') && contains(github.head_ref, 'release-please') }}
    runs-on: ubuntu-latest
    steps:
    - uses: google-github-actions/release-please-action@v3
      with:
        release-type: python
        package-name: citemplate
        token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

