name: lint and test

on:
  push:
    branches:
      - "*"
      - "!master"
      - "!main"

  pull_request:
    types:
      - closed

jobs:
  print-context-info:
    runs-on: ubuntu-latest
    steps:
    - name: Print GitHub context contents
      run: echo ${{ toJSON(github) }}

  lint-and-test:
    # we don't have to run on the release-please branch
    if: ${{ !startsWith(github.ref_name, 'release-please') }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Prepare poetry
      run: |
        poetry config virtualenvs.in-project true
        poetry install

    - name: Run ruff
      run: poetry run ruff citemplate

    - name: Run mypy
      run: poetry run mypy citemplate

    - name: Run tests with nox
      run: poetry run nox -s pytest
