name: lint and test

on:
  push:
    branches:
      - "*-dev"
  pull_request:
    types:
      - closed

jobs:
  lint-and-test:
    if: ${{ !contains(github.head_ref, 'release-please') }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Prepare poetry
      run: |
        poetry config virtualenvs.in-project true
        poetry install

    - name: Run ruff
      run: poetry run ruff citemplate

    - name: Run mypy
      run: poetry run mypy citemplate

    - name: Run tests with nox
      run: poetry run nox

  set-release-ready-label:
    # this job only runs when the tests after merging the PR to main were successful
    if: ${{ startsWith(github.ref, 'refs/heads/main') && !contains(github.head_ref, 'release-please') }}
    needs: [lint-and-test]
    runs-on: ubuntu-latest
    steps:
    - name: Add a ready-for-release to the Main Branch
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const label = 'ready-for-release';
          const context = github.context;

          console.log(`Adding label '${label}' to '${context.ref}'`);
          await github.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            labels: [label],
          });

